name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
     
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: optimisation-notes.tex
          
      - name: Upload optimisation-notes.pdf
        run: |
          # configure git
          git config --global user.name "FabsOliveira"
          git config --global user.email "fabricio.oliveira@aalto.fi"
          
          # add file and push
          git add optimisation-notes.pdf
          git commit -m "[github actions] update optimisation-notes"
          git push
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
       
